### ISSUE TITLE
upgrade main screen buttons to Image Buttons

### ISSUE THREAD

**Issue by venusaim23** [venusaim23/Android-Calculator#5]
Currently the buttons have text on them (1-9 and 0 buttons and symbols). It would be great if they were upgrade to ImageButtons with drawables instead of text on the buttons.

**Comment by unnikrishnan2002** [comment]
Hey I would like to work in this issue

**Comment by venusaim23** [comment]
> Hey I would like to work in this issue

sure you can work on it. Make sure you follow the code pattern and all the drawables are of same theme. Comment for any doubts/clarifications. Good luck!

**Comment by unnikrishnan2002** [comment]
![image](https://user-images.githubusercontent.com/76985777/139827047-e3105734-2e99-4784-8aef-7773d60d4186.png)

Hey @venusaim23 please have look at this design and suggest changes if needed

**Comment by venusaim23** [comment]
Hey @unnikrishnan2002 sorry for late. I'd like to maintain the transparent background for the buttons. So, we need not work on other drawables for a dark theme. You can add a circle to maintain the circle theme though. And the colour of numbers can be a gray shade, so the button is visible in both light and dark mode (#707070 - in the image). Special buttons like AC, back and symbols can be colorAscent of the app. Let those special buttons have the transparent background too. Just invert the colours for equal button(transparent '=' and coloured background).

![image](https://user-images.githubusercontent.com/75775529/140076288-c57e6702-4593-4bad-9439-4926cf8c5ef5.png)

 You can use Adobe XD(free) for designing these basic assets. Or I'll provide with the assets(comment if you need or not).

**Comment by unnikrishnan2002** [comment]
Hey thanks for providing such descriptive explanation but it would be convenient if you could provide the assets

**Comment by venusaim23** [comment]
> Hey thanks for providing such descriptive explanation but it would be convenient if you could provide the assets

added a folder Assets. Two themes to choose ->
![image](https://user-images.githubusercontent.com/75775529/140261999-f0451db3-9d41-4517-8ea4-61b1c3f9c1e6.png)

Choose whichever theme looks better. We'll add an option for user to select later. Add the svg files from android studio (right click drawable -> New -> Vector Asset -> Select the svg images). Follow the naming convention as "ic_buttonName". Don't change any values for the vector images. All dimensions are set.

**Comment by venusaim23** [comment]
Also delete the previous root image, so, it doesn't interfere with the existing theme.

**Comment by unnikrishnan2002** [comment]
Hey, @venusaim23  I guess there is a problem. The assets you provided are not showing in the android studio , every icons just shows the circle outline and if it is plain it shows nothing, no numbers are visible certain icons like equal , root and back only shows the inside elements , rest of all the assets just shows the blank ring.


![image](https://user-images.githubusercontent.com/76985777/140269078-9f4decf6-8d92-4ff9-a435-6948128b9833.png)

**Comment by venusaim23** [comment]
> Hey, @venusaim23 I guess there is a problem. The assets you provided are not showing in the android studio , every icons just shows the circle outline and if it is plain it shows nothing, no numbers are visible certain icons like equal , root and back only shows the inside elements , rest of all the assets just shows the blank ring.
> 
> ![image](https://user-images.githubusercontent.com/76985777/140269078-9f4decf6-8d92-4ff9-a435-6948128b9833.png)

Fixed this issue. Try again with the updated assets.

If you're interested in the issue, here's what was wrong:
The svg tags(text and tspan) weren't recognized by android studio
[This](https://stackoverflow.com/questions/50023285/android-vector-drawable-text-not-support-tspan-not-support) was helpful.
![image](https://user-images.githubusercontent.com/75775529/140285592-7e2b43f5-38b7-4859-8b85-47482c8d5dd5.png)

Converted all the shapes and texts to path and updated the repo.

**Comment by venusaim23** [comment]
Hey @unnikrishnan2002 , I noticed the icons looked small on screen. You can adjust by modifying the svg code like this:
![image](https://user-images.githubusercontent.com/75775529/140287748-214448b8-ff62-4dae-9bd3-3a5563b07e9c.png)

Put all the path tags inside group tag with attributes as mentioned. Keep the pivotX, pivotY attributes same and modify the scaleX, scaleY attributes accordingly.
For the rounded icons, modify the width and height. Scaling the image would cut the ring.

**Comment by unnikrishnan2002** [comment]
Hey thank you so much , working on it

**Comment by unnikrishnan2002** [comment]
Hey @venusaim23 do I have to provide content descriptions to the imageButtons , because I saw you have given a content description to the square root image button
